language: node_js
node_js:
- node
script:
- npm run build
- npm run test
deploy:
  provider: npm
  email: kkitokkito@gmail.com
  api_key:
    secure: RVTcPU+XhyELdScs9YzjiTtAVRiSRzJenwuNtUWQOLJIyMKV3+DA5Phz0oV0pcDy6+BUzpzsfk1r1qFG5hNIOys6JRgVeBrT6L42t5pXq5kOJelloqiD2S0rzSmCwD3/hmVggUZ+52uQfr47ijaB3uqEI9/kQcnnc2FHMf/3BbQYpG4A8d3gmB0yqE8HzqGsVvrmXwwynbnDYNLc31uXTbkcjcmEhYPiHiROxQ3oeFaKDS3VnrkMhw9YqvSVUHSmYVNDSk6QnY1xOP65pVGty5WD0mSF0CdcJ/wiva4zYpvc3UEJI7qLKpFOE/KkWGCdcYqY4enGKjkJQdXtG5opdKZK40jBXH5wjfUes/jPg50Z1RFG7PEH3RYZRMWVnuUU6f0VBijGP3zCFZcq7aXfSr+1drdGXshXqoHFgAr5JoAlUJfXNWIO/RD9Omj9Rbfa+yBigeg1/LFar+w0TtQ9Y6nNQthgJEv9gJaKaDkI2grXdiEYT5aIPJ426/Z0WDlEe83yjYW/KPd6JaZ0Uc1Hl/tpQOBeV50erR/jvfKdvnH0s7EVE+1NrXOiQ+lo6ig0QzoVkjri6iZEBoFxhazhO77UCvjVDdgRUoyQgM61sEgJQO+hFBh6lXhgujKuEiiNN8e1KZlNDRSXIQUgbbuPY0Lq7/Ir3kOSxHv03UPU2Rs=
  on:
    tags: true
    repo: kkito/drumstick
